// DRIAN AI — Power Inc
// !drian female <script> | !drian male <script> | !drian song <theme> | !drian news <headline>
const axios = require("axios");
const fs = require("fs");
const path = require("path");
const os = require("os");

const BASE = "http://localhost:5000";

async function fetchAudio(endpoint, body) {
  const r = await axios.post(`${BASE}${endpoint}`, body, {
    responseType: "arraybuffer",
    timeout: 90000,
    headers: { "Content-Type": "application/json" }
  });
  const lyrics =
    r.headers["x-lyrics"] || r.headers["x-script"] || null;
  return { buffer: Buffer.from(r.data), lyrics };
}

module.exports = {
  config: {
    name: "drian",
    aliases: ["drianai", "ai"],
    version: "2.0.0",
    author: "Power Inc",
    cooldowns: 15,
    hasPermssion: 0,
    description: "DRIAN AI Generator — jingle voice, weather voice, song, and news broadcast",
    commandCategory: "ai",
    usages: "female <script> | male <script> | song <theme> | news <headline>"
  },
  run: async ({ api, event, args }) => {
    const { senderID, threadID, messageID } = event;
    const sub = (args[0] || "").toLowerCase();
    const text = args.slice(1).join(" ").trim();

    const HELP =
      `🎙️ DRIAN AI GENERATOR\n` +
      `───────────────────────\n` +
      `!drian female <script>  — Jingle voice (Babae)\n` +
      `!drian male <script>    — Broadcast voice (Lalake)\n` +
      `!drian song <theme>     — AI kumakantang kanta\n` +
      `!drian news <headline>  — AI news broadcast\n` +
      `───────────────────────\n` +
      `Made by 👑 Power Inc`;

    if (!sub || !text) return api.sendMessage(HELP, threadID, messageID);

    const valid = { female:1, fem:1, babae:1, male:1, lalake:1, song:1, kanta:1, news:1, balita:1 };
    if (!valid[sub]) return api.sendMessage(HELP, threadID, messageID);

    api.setMessageReaction("⏳", messageID, () => {}, true);

    let endpoint, body, filename, label;
    if (sub === "female" || sub === "fem" || sub === "babae") {
      endpoint = "/api/drian/female"; body = { text, withMusic: true };
      filename = "drian-jingle.mp3"; label = "🎵 Radio Jingle Voice (Babae)";
    } else if (sub === "male" || sub === "lalake") {
      endpoint = "/api/drian/male"; body = { text };
      filename = "drian-weather.mp3"; label = "🌤️ Weather Voice (Lalake)";
    } else if (sub === "song" || sub === "kanta") {
      endpoint = "/api/drian/song"; body = { prompt: text, voice: "female" };
      filename = "drian-song.mp3"; label = "🎤 AI Song — Kumakanta";
    } else {
      endpoint = "/api/drian/news"; body = { headline: text, withMusic: false };
      filename = "drian-news.mp3"; label = "📺 Power Inc News Broadcast";
    }

    try {
      const { buffer, lyrics } = await fetchAudio(endpoint, body);
      const tmp = path.join(os.tmpdir(), `drian_${Date.now()}_${filename}`);
      fs.writeFileSync(tmp, buffer);

      const msg = {
        body: `${label}\n━━━━━━━━━━━━━━━━\n` +
              (lyrics ? `📝 ${decodeURIComponent(lyrics).slice(0, 300)}\n━━━━━━━━━━━━━━━━\n` : "") +
              `🎙️ Generated by DRIAN AI\n👑 Power Inc`,
        attachment: fs.createReadStream(tmp)
      };

      api.sendMessage(msg, threadID, () => {
        try { fs.unlinkSync(tmp); } catch {}
      }, messageID);
      api.setMessageReaction("🎵", messageID, () => {}, true);
    } catch (e) {
      api.setMessageReaction("❌", messageID, () => {}, true);
      return api.sendMessage(`❌ DRIAN AI Error: ${e.message}`, threadID, messageID);
    }
  }
};
